# this is for http://localhost:8080/
google:
  CLIENTID: google
  SECRET: google
  CALLBACK: http://localhost:8080/auth/google/callback
github:
  CLIENTID: github
  SECRET: github
  CALLBACK: http://localhost:8080/auth/github/callback
